### ISSUE TITLE
System.OutOfMemoryException: An exception of type 'System. OutOfMemoryException' was thrown

### ISSUE THREAD

**Issue by JiangWeian** [DICOMcloud/DICOMcloud#65]
If I send multiple-frame image that have 200-300MB to the StowRS interface frequently, WebApi will throw an exception when the memory usage is large.
The exception is: System.IO.IOException: Error writing MIME multipart body part to output stream. ---> System.OutOfMemoryException: An exception of type 'System. OutOfMemoryException' was thrown.
But I still have 30% of my memory. My WebApi published in IIS, that version is 7.0.0.0
And in the client side, I use the Httpwebrequest object to send request data.

Is this problem related to the recycling mechanism of .net LOH (large object heap)? It is said that in .net, large objects should be decomposed into small objects with size less than 85000 bytes.

Is there a solution for me?

**Comment by JiangWeian** [comment]
And the Stack trace is here:
System.IO.IOException: Error writing MIME multipart body part to output stream. ---> System.OutOfMemoryException: An exception of type 'System. OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.MimeBodyPart.<WriteSegment>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContentMultipartExtensions.<MultipartReadAsync>d__10.MoveNext()
   ......

**Comment by Zaid-Safadi** [comment]
@JiangWeian do you have an example that I can use to reproduce this?

**Comment by JiangWeian** [comment]
OK, I have find the reason. In client I use HttpWebRequest object under .net 4.0. If I change it to .net 4.5, I get no exception. I will close the issue if it's right after a lot of testing.

**Comment by Zaid-Safadi** [comment]
Interesting, not sure why the client affect the memory behavior on the server. I'll be interested to learn more about this if you got some additional details @JiangWeian

**Comment by JiangWeian** [comment]
I think .net 4.5 should be an optimization of HttpWebRequest class. At present, it will not throw the exception of 'System.OutOfMemoryException' in WebApi, but sometimes the client will occur some error when the network is not good. It may not be send to WebApi when the data is not completely written to the stream.
